# Generated by Django 3.2.25 on 2024-05-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20240517_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='entry_id',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
    ]
