# Generated by Django 5.0.4 on 2024-05-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='total_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='useful_answers',
            field=models.IntegerField(default=0),
        ),
    ]
