# Generated by Django 5.0.4 on 2024-05-16 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_estudiante_total_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='rol',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='accounts.roles'),
        ),
    ]
