# Generated by Django 5.0.4 on 2024-05-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_estudiante_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='rol',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
